### ISSUE TITLE
ansible.cfg presence in root might break installation from repository

### ISSUE THREAD

**Issue by EamonTracey** [redhat-cop/ah_configuration#280]
Collections do not ship with an `ansible.cfg` but this repository has one in the root directory. Therefore, if someone builds/installs the collection from the repository using commands like:
```bash
git clone https://github.com/ansible/automation_hub_collection
cd automation_hub_collection
ansible-galaxy collection build -vvv
ansible-galaxy install ansible-automation_hub*.tar.gz
```
then the `ansible.cfg` in the repository will override other settings.

It looks like the `ansible.cfg` is used for some tests, so it might be better to keep it elsewhere in the repository, not in the root directory.

**Comment by sean-m-sullivan** [comment]
Generally they can't do that because we variablized the galaxy.yml, which helps with the multiple namespaces as well. I'd be interested in other peoples views on this, as we did use to keep it in the .github folder and copy it to main as part of our workflow.

**Comment by Tompage1994** [comment]
Personally, I don't like it being in the main for this or for the other collections as it can (and does in the case of controller_configuration) break my (and presumably others') dev workflows. I also think we should revisit the galaxy.yml being in the collection because it would be good if you could install firstly from the repo. As part of the release process we could make it so that the galaxy.yml that is created get updated in the repo. Potentially we append `-dev` to the version number so it differs from the released version?

Regarding the ansible.cfg I definitely think we should move it out though

**Comment by sean-m-sullivan** [comment]
I like this change, we keep templating it, but have a persistent copy, best of methods
