### ISSUE TITLE
Confusion in Permission vs Roles assignment using modules

### ISSUE THREAD

**Issue by nodje** [redhat-cop/ah_configuration#312]
using 2.0.2

As far as I understand from the UI:
- Roles can be created and affected Permissions
- Groups can be created and affected Roles
That's it.

Looking at the different modules of this collection, I find out that:

`group_roles` allows affecting Roles to Groups **but also on specific target objects** And that notion doesn't show in UI. 
I'll make some manual testing but I really wonder how it translates in the UI

`namespace` allows affecting `A list [...] of groups that own the Namespace.` and even an undocumented `object_roles` which probably allows to affect Permissions (and not roles) to what? groups that are supposed to be owners ? --> very confusing to me

It'd be nice to clarify how this is supposed to work.
I'd much rather have a unique place to affect roles to group.

As for the `targets` of group roles, that's needed but is this only a temporary shortcoming of the UI? Does it work as expected even though it doesn't show ?

**Comment by sean-m-sullivan** [comment]
As per
https://issues.redhat.com/browse/AAH-2677

You are correct, the GUI does not show the granular permissions when assigned to objects.

This is built on how we wanted the controller roles to work. The idea being that you set A group, or A list of groups and give them sets of permissions, The role/module doesn't care if it doesn't make sense to give two groups access to the same namespace, it just does it. 

And you could create entries that just for each group, setting up separate list entries to define that groups permissions. I just wrote the module to be flexible, So that if you wanted to give multiple groups the same permission, it was possible as well. 

The targets are only for giving permission over specific things in Hub. Right now the GUI grants GLOBAL permissions, for example if you give it the namespace role, it grants permission on EVERY namespace. 

If you open the issue linked above you can see how it ends up showing in the API each groups permissions, as its a separate entity. The role/module just allows for groupings.

**Comment by nodje** [comment]
thanks, I upvoted the issue.

I think Namespace module object_roles property should be documented though.

**Comment by sean-m-sullivan** [comment]
@nodje how would you suggest we change the wording we have

groups - List of Group Names to apply the roles to.
role_list - The list of roles to add to or remove from the given group. See below for options.
collection_namespaces - List of collection namespaces to apply the roles to.

Its the three combined that make the final definition.

**Comment by nodje** [comment]
I gather you're talking about the group_roles README.md.

If I'm not mistaken, I think it's trickier than that because :

- a set of Permission is ASSIGNED TO a Role
- a Role is ASSIGNED TO Group/Groups
So then, according to the chosen Permission for the Role, it may APPLY to specific objects (Collection Namespaces, Collections, etc. )

Maybe target objects should be linked to Permissions and then Permissions assigned to Role.

In the end it's the Permission on a target object (or all objects is none specified) that provides the right to do things.

A Role is only a set of Permission.
And a Group a set of User the Permissions will be given to.


From the Namespace point of view then, I'm not sure users should have the possibility to define usage rights upon creation. 
- if it's possible for Namespaces then it should also be possible for other Objects.
- it seems too complex to provide the ability to define Permissions<Roles<Groups at this level.

Maybe there's a shortcut as the doc seems to indicate where you can assign Permissions for that Namespace for Group/Groups. but this isn't consistent with the Permissions<Roles<Groups hierarchy.

If Permissions<Groups is permitted then the possibility needs to be available in the group_roles module and obviously in the UI at some point.

This isn't easy.

My 2c
HTH
