### ISSUE TITLE
infra.ah_configuration collection_repository_sync (version 2.0.3) documentation is wrong

### ISSUE THREAD

**Issue by BryceTant** [redhat-cop/ah_configuration#314]
# Summary

Documentation for collection version 2.0.3 still lists ah_token as a variable for the collection_repository_sync role. Upon testing this role, the variable is not accepted. ah_username and ah_password are the expected variables.

# Issue Type

- Bug Report
- Documentation Bug Report

**Comment by usa-usa-usa-usa** [comment]
Came here to post the same issue. I am seeing the same problem with `collection_remote`. I am using the same version as @BryceTant, trying to configure AH in AAP 2.4.

Although I believe this to be more than just an issue with the documentation being incorrect. We have been using these collections since July of last year. We are setting an `ah_token` var as well as `ah_username` and `ah_password`. The call to the `collection_remote` module in `ah_configuration/roles/collection_remote/tasks/main.yml` is passing `ah_token` when the modules argument spec in the module does not have it defined.

**Comment by sean-m-sullivan** [comment]
This is correct, and the documentation is wrong, the module and underlying things do not support ah_token, I am looking at our current doc fragments and how it is done, to support it more, if I don't find a way forward by Monday, I'll fix the docs, but until then use ah_username/password. Things need to be adapted and tested under the hood to change it.

**Comment by usa-usa-usa-usa** [comment]
Just adding a comment here, our workaround for this is to stop calling the roles at the play level. While `ah_token` cannot be defined for the collection_remote/repo stuff, it is still needed for mostly everything else we use (`namespace`, `ee_registry`, `ee_repository`, etc...). So the only way to pass/omit `ah_token` is to specify it explicitly in the `vars` on an `include_role` task.

**Comment by djdanielsson** [comment]
@sean-m-sullivan can we close this now?

**Comment by sean-m-sullivan** [comment]
Was hoping to release an update that made token more available, but we are at the mercy of the galaxy_ng/hub api, right now coillection allows all options available.
